### ISSUE TITLE
Question: why does no-case remove non-word characters?

### ISSUE THREAD

**Issue by wmaurer** [blakeembrey/no-case#13]
Hi, thanks for your `change-case` npm module. I'm using it in my VSCode extension: [vs-code-change-case](https://github.com/wmaurer/vscode-change-case) 

A user has reported that title case is stripping special characters (wmaurer/vscode-change-case#10).

I see that `title-case` and a number of other functions are using `no-case` which strips non-word characters. Other functions, e.g. `upper-case` don't use `no-case` and don't strip non-word characters. To me there's a an inconsistency here, so I thought I'd ask you what's the reasoning behind this?

Cheers

**Comment by blakeembrey** [comment]
All the libraries that change case types (E.g. camel, pascal, etc) strip special characters because there's no way to handle them consistently. What would be the expected behaviour to camel case special characters? Either way, the library won't be changed away from this. However, the linked issue explicitly described `title-case` which the goal is to `Make Something Like This`. The goal is not, however, to do proper AP Title casing with rules. If that is the goal, a different library should probably used for that. There has been a similar issue in the past, but it's just not something I need.

**Comment by wmaurer** [comment]
Thanks for the clarification.
There's probably something I can do on my side to achieve the user's expected result, and still continue using your library.

Cheers

**Comment by blakeembrey** [comment]
I'd do a search for proper "title case" modules. I know it should be pretty quick to build 😄  FWIW, I love the VSCode plugin myself!

I found https://www.npmjs.com/package/to-title-case which fits the bill. I'd be happy to refactor the `title-case` module and release a new major of `change-case` supporting more "proper" title casing, just knowing the rest of the modules will continue to act the same.
